### ISSUE TITLE
Cenum is not a subtype of Integer

### ISSUE THREAD

**Issue by melonedo** [JuliaInterop/CEnum.jl#14]
With respect to https://github.com/JuliaLang/Downloads.jl/pull/134, in the C language, `enum` is just an alias for some integer type. However, CEnum is not a subtype of `Integer`, and it does not support all integer methods, `zero` for example.
https://github.com/JuliaInterop/CEnum.jl/blob/433d4ec1cae51c1bd6b8ff4f4085048ca4a44e92/src/CEnum.jl#L15

**Comment by Gnimuc** [comment]
`Integer` is a `Number`, I don't think `enum` is a number because we usually use it in the style of a name, not a number(even though there is a number behind that name). 

In practice, you could explicitly convert a `Cenum` to a `Integer`, so it doesn't matter whether `Cenum` is a subtype of `Integer` or not.
