### ISSUE TITLE
Result type of bitwise operations

### ISSUE THREAD

**Issue by maleadt** [JuliaInterop/CEnum.jl#3]
If you and/or/xor two enum values together, the result is a UInt:

```julia
julia> using CEnum

julia> @cenum(Flag, x, y)
y(1)

julia> x
x(0)

julia> y
y(1)

julia> x | y
0x00000001
```

Although this makes sense, since `x|y` isn't necessarily representable as a value of this enum, it's annoying when combined with method signatures:

```julia
julia> foobar(flag::Flag) = nothing
foobar (generic function with 1 method)

julia> foobar(x)

julia> foobar(y)

julia> foobar(x | y)
ERROR: MethodError: no method matching foobar(::UInt32)
```

I used to have this definition for my enums, but that would need a fix of the showing code:

```julia
julia> using CEnum

julia> @cenum(Flag, x=1, y=2)
y(2)

julia> Base.:|(x::Flag, y::Flag) = reinterpret(Flag, Base.cconvert(Unsigned, x) | Base.cconvert(Unsigned, y))

julia> Base.cconvert(Unsigned, x | y)
0x00000003

julia> x | y
Error showing value of type Flag:
ERROR: Invalid enum: 3, name not found
```

**Comment by Gnimuc** [comment]
Embarrassingly, there are also [situations](https://github.com/JuliaGPU/VulkanCore.jl/issues/15#issuecomment-361954931) where the current choice works better. In addition, Julia functions are usually loosely typed, so the solution might be just removing the annotation or using something like `foobar(flag::Union{Flag,UInt32}) = nothing`. 

```
julia> x | y
Error showing value of type Flag:
ERROR: Invalid enum: 3, name not found

julia> Flag(x | y);
ERROR: ArgumentError: invalid value for Enum Flag: 3
```
In Julia, this is the expected behavior since `3` is indeed not a member of `Flag`, but in C/C++, that's [a completely different story](https://stackoverflow.com/questions/18195312/what-happens-if-you-static-cast-invalid-value-to-enum-class). I guess @SimonDanisch originally implemented this just based on Julia's enum implementation, so this behavior was copied as well.

**Comment by SimonDanisch** [comment]
> I guess @SimonDanisch originally implemented this just based on Julia's enum implementation, so this behavior was copied as well.

It has been ages since I wrote this, but I faintly remember cases where the non representability was problematic, so I think I just went with the simplest fix for that ;)

**Comment by maleadt** [comment]
> Julia functions are usually loosely typed, so the solution might be just removing the annotation

Of course, but that's just sidestepping the issue :-) Sometimes you might need to add a type, for dispatch or ambiguity reasons. I guess I expected the operation to be internal, always yielding a (possibly unrepresentable) enum.

**Comment by Gnimuc** [comment]
tagged: https://github.com/JuliaRegistries/General/pull/2320
